//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInformation
    {
        public int ID { get; set; }
        public string AccountHolder { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
