//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateCommented { get; set; }
        public int RegID { get; set; }
        public string PostedBy { get; set; }
    }
}
