//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerShop
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShopCustomerID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ShopCustomer ShopCustomer { get; set; }
        public virtual User User { get; set; }
    }
}
