//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityVerification
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int UploadStatus { get; set; }
        public Nullable<int> VerifyByUserID { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<int> VerificationStatus { get; set; }
        public string VerificationNote { get; set; }
        public string ImgSrc { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
