//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTraining
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public Nullable<int> SexID { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> StateOriginID { get; set; }
        public string LGAResidence { get; set; }
        public Nullable<int> StateResidenceID { get; set; }
        public string City { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    
        public virtual Sex Sex { get; set; }
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
    }
}
