//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderNegotiations = new HashSet<OrderNegotiation>();
            this.ShippingInformations = new HashSet<ShippingInformation>();
            this.TempPendingPayments = new HashSet<TempPendingPayment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShopCustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SubProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public string PaymentRef { get; set; }
        public string PaymentChannel { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public string OnCart { get; set; }
        public Nullable<System.TimeSpan> TimePaid { get; set; }
        public string ProductName { get; set; }
        public string SubProductName { get; set; }
        public string Negotiated { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<System.DateTime> DateSentforDelivery { get; set; }
        public Nullable<decimal> SellersMoney { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public Nullable<int> DeliveredByAgentAllocationID { get; set; }
        public string OrderGroupID { get; set; }
    
        public virtual User User { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductSubProduct ProductSubProduct { get; set; }
        public virtual ShopCustomer ShopCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderNegotiation> OrderNegotiations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShippingInformation> ShippingInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempPendingPayment> TempPendingPayments { get; set; }
    }
}
