//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurLead
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
