//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
            this.PopularProducts = new HashSet<PopularProduct>();
            this.ProductSubProducts = new HashSet<ProductSubProduct>();
            this.ProductVisits = new HashSet<ProductVisit>();
            this.SearchOptimizations = new HashSet<SearchOptimization>();
            this.SocialMediaAds = new HashSet<SocialMediaAd>();
        }
    
        public int ID { get; set; }
        public int ShopID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> QuantityinStock { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Published { get; set; }
        public Nullable<int> Ready_for_Publishing { get; set; }
        public string Negotiable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopularProduct> PopularProducts { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductStatu ProductStatu { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSubProduct> ProductSubProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVisit> ProductVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchOptimization> SearchOptimizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaAd> SocialMediaAds { get; set; }
    }
}
