//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSubProduct()
        {
            this.Orders = new HashSet<Order>();
            this.PopularProducts = new HashSet<PopularProduct>();
            this.ProductVisits = new HashSet<ProductVisit>();
            this.SearchOptimizations = new HashSet<SearchOptimization>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductStatusID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> QuantityinStock { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string Currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopularProduct> PopularProducts { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductStatu ProductStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVisit> ProductVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchOptimization> SearchOptimizations { get; set; }
    }
}
