//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public string AboutSection1 { get; set; }
        public string AboutSection2 { get; set; }
        public string AboutSection3 { get; set; }
        public string AboutSection4 { get; set; }
        public Nullable<int> OpenandCloseCBTTest { get; set; }
        public Nullable<int> ApplicationClosed { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> BonusPercentage { get; set; }
        public Nullable<int> Payment_Account_Activation { get; set; }
        public Nullable<int> LogoMobile { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
    }
}
