//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopAPIKey
    {
        public int ID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string APIKey { get; set; }
        public string Status { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
