//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaAd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialMediaAd()
        {
            this.SocialMediaAdsStatistics = new HashSet<SocialMediaAdsStatistic>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SocialMediaChannelID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string Country { get; set; }
        public string Locations { get; set; }
        public string TargetPeople { get; set; }
        public Nullable<int> TotalDaysPaid { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> AdsStatus { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<int> DaysActive { get; set; }
        public Nullable<int> LaunchYear { get; set; }
        public Nullable<int> LaunchMonth { get; set; }
        public Nullable<int> LaunchDay { get; set; }
        public Nullable<int> PreviousYear { get; set; }
        public Nullable<int> PreviousMonth { get; set; }
        public Nullable<int> PreviousDay { get; set; }
    
        public virtual PopularStoreStatu PopularStoreStatu { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SocialMediaChannel SocialMediaChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialMediaAdsStatistic> SocialMediaAdsStatistics { get; set; }
    }
}
