//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int ID { get; set; }
        public string Testimonial1 { get; set; }
        public string Postedby { get; set; }
        public string Position { get; set; }
    }
}
