//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myvshoponline
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBonu
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> PercentageDiscount { get; set; }
        public Nullable<decimal> ExpectedAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> PercentageExtraBonus { get; set; }
        public Nullable<decimal> ExtraBonusAmount { get; set; }
        public Nullable<int> ExtraPeriod { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
